Default: &defaults
  host: "*4" # any IPv4 host
  port: 8000
  approot: "http://localhost:8000"
  copyright: Chris © 2014

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://two-wrongs.com"
  port: 8989
  <<: *defaults
